packages:
  - apps/*
  - packages/*
  - spikes
allowBuilds:
  '@google/genai': true
  electron: true
  electron-winstaller: false
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - markstream-react@2.0.3
  - '@types/react-dom@19.2.5'
